### ISSUE TITLE
Information on how to wire the rdm6300 to the pi no more available. 

### ISSUE THREAD

**Issue by Ja83La** [mad-tinkerer/python-rdm6300#2]
Unfortunately the website https://the.mad-tinkerer.me/rdm-6300-raspberry-pi/ is down. 
May you upload the wiring information here on the github site?
Most likely the article refers to 3v3 TTL levels vs 5v levels. 
I succeeded using two 2k2 resistors to create a voltage separator (e.g. https://gist.github.com/andrewvaughan/dc51a0370db1ec159d390c1b3a8b320a).

**Comment by mad-tinkerer** [comment]
Thank you Ja83La, unfortunately, the original site went down, I will try to find an easier way to host these contents.

I have moved the referenced article and also added an image of the wiring to the README.md.

But essentially you are correct, you will need a voltage divider as you suggested.
